### ISSUE TITLE
distill template

### ISSUE THREAD

**Issue by richpauloo** [ryanpeek/WRDS_intro#2]
initial distill template for the site - footer, site yaml, etc.

**Comment by richpauloo** [comment]
Sorry I know you're technically on this, but I got stoked on formatting and went ahead and submitted a PR #20  that addresses this.

**Comment by ryanpeek** [comment]
No worries, thanks for taking care of this. Definitely good to make some progress. I added a small tweak to the highlighting, but beyond that I think it's a good shell default. I played around with some different options, and I think Distill defaults are really quite nice and clean...good spacing and font kerning, easy to read, so I like much of that already. 

I would like to keep some of the css that I used in setting up the old site, because I had some special stuff setup to set the objective boxes at the start of lessons, signify challenges, and for making the dropdown boxes look nice (green arrows). So might want to add that back in...but we can use the Distill default and paste in just the bits we want.

**Comment by richpauloo** [comment]
Oh no! I'm sorry @ryanpeek if I accidentally deleted css. I haven't explored those extra touches you've added, but look forward to discovering and reusing those templates in the modules I write. I'll look out for them in your modules to use as examples and I'm sure I'll end up factoring lessons as I learn more.

Agree that the distill defaults do a great job of laying out info. I love the table of contents look and feel, as well as the asides.
